import { MyProvider } from "@/components/AppProvider";
import "./globals.css";
import styles from "./page.module.css";

const name = process.env.USER;

export const metadata = {
  title: `User ${name}`,
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({ children }) {
  const user = { name };

  return (
    <html lang="en">
      <body>
        <main className={styles.main}>
          <div>
            <Link href="/">Home</Link>
            <Link href="/friends/1">First Friend</Link>
            <Link href="/friends/2">Second Friend</Link>
          </div>
          <h1>Users name is {name}</h1>
          <MyProvider user={user}>{children}</MyProvider>
        </main>
      </body>
    </html>
  );
}
