const name = [...process.env.USER].reverse().join("");

export const metadata = {
  title: `Friend ${name}`,
  description: "Generated by create next app",
};

export default function FriendLayout({ children, params }) {
  return (
    <div>
      <h3>Friends name is {name}</h3>
      {children}
    </div>
  );
}
