const name = [...process.env.USER].reverse().join("");

export const metadata = {
  title: `Friend ${name}`,
  description: "Generated by create next app",
};

export default function FriendLayout({ children, params }) {
  return (
    <div className="cleint">
      <h3>Friend Layout.js</h3>
      <h4>Friends name is {name}</h4>
      {children}
    </div>
  );
}
